package mselector

var (
	// MahjongGYTile108 108张贵阳麻将
	MahjongGYTile108 = []int{
		// 万
		MAHJONG_CRAK1, MAHJONG_CRAK1, MAHJONG_CRAK1, MAHJONG_CRAK1,
		MAHJONG_CRAK2, MAHJONG_CRAK2, MAHJONG_CRAK2, MAHJONG_CRAK2,
		MAHJONG_CRAK3, MAHJONG_CRAK3, MAHJONG_CRAK3, MAHJONG_CRAK3,
		MAHJONG_CRAK4, MAHJONG_CRAK4, MAHJONG_CRAK4, MAHJONG_CRAK4,
		MAHJONG_CRAK5, MAHJONG_CRAK5, MAHJONG_CRAK5, MAHJONG_CRAK5,
		MAHJONG_CRAK6, MAHJONG_CRAK6, MAHJONG_CRAK6, MAHJONG_CRAK6,
		MAHJONG_CRAK7, MAHJONG_CRAK7, MAHJONG_CRAK7, MAHJONG_CRAK7,
		MAHJONG_CRAK8, MAHJONG_CRAK8, MAHJONG_CRAK8, MAHJONG_CRAK8,
		MAHJONG_CRAK9, MAHJONG_CRAK9, MAHJONG_CRAK9, MAHJONG_CRAK9,

		// 筒
		MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1,
		MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2,
		MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3,
		MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4,
		MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5,
		MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6,
		MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7,
		MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8,
		MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9,

		// 条
		MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1,
		MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2,
		MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3,
		MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4,
		MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5,
		MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6,
		MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7,
		MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8,
		MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9,
	}
	// MahjongGYTile72 贵阳72张牌列表
	MahjongGYTile72 = []int{
		// 筒
		MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1,
		MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2,
		MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3,
		MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4,
		MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5,
		MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6,
		MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7,
		MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8,
		MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9,

		// 条
		MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1,
		MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2,
		MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3,
		MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4,
		MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5,
		MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6,
		MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7,
		MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8,
		MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9,
	}
	// MahjongGYTile36 贵阳36张牌列表
	MahjongGYTile36 = []int{
		// 筒
		MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1,
		MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2,
		MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3,
		MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4,
		MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5,
		MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6,
		MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7,
		MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8,
		MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9,
	}
)
